### ISSUE TITLE
requireNativeComponent: "BarcodeView" was not found in the UIManager.

### ISSUE THREAD

**Issue by asko328P** [reeq-dev/react-native-pdf417#1]
I tried to use the component inside a View but then I got this error:
Invariant Violation: requireNativeComponent: "BarcodeView" was not found in the UIManager.

I followed the installation guide and copied the example code. Is there something else that I need to add to use this package?

**Comment by reeq-dev** [comment]
@asko328P 
What version of react-native do you have, also could you provide a platform ?

**Comment by asko328P** [comment]
Sorry, I should have written it down right away. I am using "react-native": "0.71.8" with "expo": "48.0.7" and Expo Go. The error occured on Android and IOS.

**Comment by reeq-dev** [comment]
@asko328P 
I've never tested this lib for expo go, and im not sure if expo is actually supporting third-party libraries, but i found this page on official documentation:
https://docs.expo.dev/workflow/using-libraries/#third-party-libraries

**Comment by asko328P** [comment]
Okay, thank you for your time. 

All the best
